### ISSUE TITLE
Tournament result icons could be more readable

### ISSUE THREAD

**Issue by guigas7** [Sendouc/sendou.ink#1008]
Opened someone's profile today and really didn't know if that was gold or bronze, the icon is very small in desktop and there's no text on hover. Just a small adjustment i think could be improved

![image](https://user-images.githubusercontent.com/11247506/195225992-2487d118-bf9c-47b8-8ec6-2412ee83200d.png)

**Comment by Sendouc** [comment]
Yeah it's currently just using the emoji from your OS but if someone knows of a free to use nice looking SVG then let's switch for sure.

**Comment by remmycat** [comment]
What do you think of these medals I designed? 🙂 
I gave myself a little challenge by trying to copy the style of the Splatoon 3 badges

(And no worries if you hate it, I felt like spending the time on trying this out anyway)

<img width="428" alt="Screenshot 2022-10-14 at 20 59 27" src="https://user-images.githubusercontent.com/3317423/195921331-e556e270-95bb-4d99-97ef-f7fb3f7e46fc.png">


![bronze](https://user-images.githubusercontent.com/3317423/195919679-2d43fdc2-d197-44a3-851d-6e7df69747b5.svg)
![silver](https://user-images.githubusercontent.com/3317423/195919681-abf1678b-3a27-4301-b026-079a4cc7328a.svg)
![gold](https://user-images.githubusercontent.com/3317423/195919683-36de5b82-5a45-4b20-89a2-c52c5228da2c.svg)

**Comment by Sendouc** [comment]
Awesome work! I love these 😍 💯 

Do you want to make a pull request to make the switch? :)

**Comment by remmycat** [comment]
Sure, will do!
