### ISSUE TITLE
New calendar event form dropdown to insta-select pool of your previous tournament

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1013]
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/38327916/195934936-c3ad8b34-55fb-4806-9837-7248232cb6db.png">

**Comment by Sendouc** [comment]
- Add in loader to fetch your last 5 (or something) map pools from your previous calendar events. Needs some new SQL
- When enabling the map pool show dropdown that insta-selects the map pool of your previous tournament.

This feature is quite useful + reduces potential mistakes if you have for example a weekly with the same map pool everytime.

**Comment by remmycat** [comment]
I'm trying to implement this, though I'm planning to make it a combobox where your own recent events show up first, but you can search for any event, not just your own.
I think that's probably neat if you wanna copy a related event's list or if you use different TO accounts for the same series.

**Comment by Sendouc** [comment]
Ah yes that's a great idea. Sounds very useful.
