### ISSUE TITLE
Allow users to highlight results

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1019]
When users have a lot of results they might want to show their best results first. For this case let's allow users to pick any number of results that shows first before other results.

- implement new action on user results page.
- form UI can be for example toggles per event name

UI can be something like:

```
> Highlighted results
Table with highlighted results ordered by date 

> Other results
Table with non-highlighted results ordered by date 
```

Where highlighted result is a title and other results is a title or maybe accordion?

## Current situation:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/38327916/196030800-b302acae-5aeb-4bab-82f3-048f6f1e545c.png">

**Comment by remmycat** [comment]
I would like to try to implement this 🙂
