### ISSUE TITLE
Articles page (new route)

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1025]
Implement https://sendou.ink/a page.

Problem: currently only 3 latest articles are shown. We should implement a new page that lists all the articles in descending chronological order. Needs nothing fancy like pagination just a simple list that looks the same as on front page is enough (bonus would be to add a small preview).

Then link should be added to it from front page. I don't believe this new page needs to be added to the Menu yet.

**Comment by ElementUser** [comment]
I'll look into this one, I never worked on Remix & didn't know its routing was file-system based, so it took me a while to find that out

**Comment by Sendouc** [comment]
Go for it! And yeah the file system router is pretty nifty in the end. Their docs are also top notch https://remix.run/docs/en/v1

**Comment by ElementUser** [comment]
Added PR here: https://github.com/Sendouc/sendou.ink/pull/1072

**Comment by ElementUser** [comment]
Just looking through some of the issues I've worked on in the past & I believe this issue can be closed now =)
