### ISSUE TITLE
Users search page

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1032]
Something like https://spl2.sendou.ink/u but exact implementation can be different.

Currently there is no way to search for a user on the site. Should be able to search by at least discord name, twitter name or splatoon 3 name (= in game name).

`useUsers` hook fetches all users and filtering can be done client side. Alternatively could do the filtering server side.

**Comment by ElementUser** [comment]
I want to take a shot at this, though it will take a little longer than my usual PRs since this one looks more difficult to do thoroughly

**Comment by ElementUser** [comment]
@Sendouc do you still have the code for that part of the web page? I should be able to adapt the dynamic list rendering part for the Splatoon 3 website. Tbh the fancy frontend part of the search is probably the hardest thing to get right :D

**Comment by ElementUser** [comment]
Thank you @Sendouc 

I have a few questions after I started on it:

- Backend: does the `/users` endpoint get users with Twitter info or Splatoon 3 tag info? In my local client with the seeding, I don't seem to see that info anywhere: http://localhost:5800/users
- Frontend: do we use any CSS frameworks? From what I can see, we do not, and right now I'm starting off by porting the CSS manually for the UI component for the User Search Results

**Comment by ElementUser** [comment]
@Sendouc also, here is the progress so far (only for the UI component):

![image](https://user-images.githubusercontent.com/15804376/199379064-4e8082ee-9fc0-4253-8c3a-6e0e98563591.png)

I spent quite a bit of time copying over the CSS & renaming everything so it makes sense (as well as renaming the CSS vars used by the old Splatoon 2 CSS)

**Comment by Sendouc** [comment]
> * Backend: does the `/users` endpoint get users with Twitter info or Splatoon 3 tag info? In my local client with the seeding, I don't seem to see that info anywhere: http://localhost:5800/users

https://github.com/Sendouc/sendou.ink/blob/rewrite/app/routes/users.tsx

Logic is here. However adding fields can be problematic. Should check how big this is response is in prod and how much bigger adding new fields would make it approximately. But if not that then we should do the search serverside which of course is more complex and not fully sure how to approach that problem (although SQLite should be able to handle it)

> * Frontend: do we use any CSS frameworks? From what I can see, we do not, and right now I'm starting off by porting the CSS manually for the UI component for the User Search Results

We don't

**Comment by ElementUser** [comment]
> > * Backend: does the `/users` endpoint get users with Twitter info or Splatoon 3 tag info? In my local client with the seeding, I don't seem to see that info anywhere: http://localhost:5800/users
> 
> https://github.com/Sendouc/sendou.ink/blob/rewrite/app/routes/users.tsx
> 
> Logic is here. However adding fields can be problematic. Should check how big this is response is in prod and how much bigger adding new fields would make it approximately. But if not that then we should do the search serverside which of course is more complex and not fully sure how to approach that problem (although SQLite should be able to handle it)

The current response in PROD when I checked just now (and copy-pasted everything into a `.txt` file) is 1.741 kB large (so a little under 2 MB).

**Comment by Sendouc** [comment]
Yup very good points and I think your idea with the code is smart as well. I think this is what we should do.

**Comment by Illya9999** [comment]
I have touched up the code to make it more memory efficient and also probably faster. You will have to add an SQL statement for the db querying though
```js
/* TODO: add user type maybe idk, i dont use typescript much */
/* TODO: add type descriptors */


let lastLoad = 0;
let cachedUsers = new Map(); /* <number, user> */

/* TODO: potentially limit amount of caches */
let cachedResults = new Map(); /* <string, number[]> */



export const loader: LoaderFunction = ({ params }: LoaderArgs) => {
  /* update cache every 10 mins */
  if(Date.now() - lastLoad > 10 * 60 * 1000) {
    cachedResults.clear();
    cachedUsers = new Map(db.users.findAll().map((u) => ([
      u.id,
      {
        id: u.id,
        discordFullName: discordFullName(u),
        discordId: u.discordId,
        plusTier: u.plusTier,
      }
    ])));
    lastLoad = Date.now();
  }
  if(!params['s'] || typeof params['s'] !== 'string') {
    /* TODO: tell them they sent invalid shit */
    throw new Response(null, { status: 404 });
  }
  let cleaned = params['s'].trim().toLowerCase();
  /* idk how long discord name limit is so i just put 12 */
  if(cleaned.length < 2 || cleaned.length > 12) {
    /* TODO: tell them they sent invalid shit */
    throw new Response(null, { status: 404 });
  }
  if(cachedResults.has(cleaned)) {
    return json<UsersLoaderData>({
      users: cachedResults.get(cleaned), /*TODO: potentially limit amount per page? */
    });
  } else {
    /* TODO: add this function to the db
        have it use sql to compare as that should be faster and return an array of user ids
        this should be much faster than comparing in javascript and the way cached results
        are stored should make it more memory efficient than the previous code by reusing
        object refrences
    */
    let search = db.users.findLike(cleaned)
      .filter(uid => cachedUsers.has(uid)) /* if a new user gets added between the time the users were cached and when the search happens we need to remove them from the results */
      .map(uid => cachedUsers.get(uid));
    cachedResults.set(cleaned, search);
    return json<UsersLoaderData>({
      users: search
    });
  }
};
```
