### ISSUE TITLE
Analyzer ability icons appear clickable

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1036]
They are not buttons so should not have that cursor + active effect:

https://user-images.githubusercontent.com/38327916/197572886-89abbda0-9510-4ba1-9fb4-7be6b4346cad.mov

**Comment by remmycat** [comment]
Probably the same component anyway, but the same goes for the icons in the dmg calc analyzer 🙂

**Comment by ElementUser** [comment]
I submitted a PR here: https://github.com/Sendouc/sendou.ink/pull/1057
