### ISSUE TITLE
Page title as H1

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1043]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/38327916/198055902-5cd4a758-03b4-43ee-8a2f-97dd82f4a326.png">

To improve our semantic HTML this should be H1. It should look the same though.

**Comment by ElementUser** [comment]
Hi @Sendouc , just looking for issues with `help wanted` tags to see if I can do anything:

Few quick questions on this task:
- Are you referring to the oval-shaped UI buttons on the left side of a page? e.g.: 
![image](https://user-images.githubusercontent.com/15804376/198389727-bc4d1c6c-b099-44c7-9cbe-d2243077960b.png)

- If so, I literally changed the `<div> </div>` elements to `<h1> </h1>` elements and it looks exactly the same (file: app/components/layout/index.tsx):

![image](https://user-images.githubusercontent.com/15804376/198389885-40338dee-778f-4816-b75c-dc399a280139.png)


If this is actually the change you want, I can submit a PR really quick. But wanted to ask before I made the PR

**Comment by ElementUser** [comment]
Great, will submit soon then
