### ISSUE TITLE
Theme choice does not persist when the browser session is terminated

### ISSUE THREAD

**Issue by ElementUser** [Sendouc/sendou.ink#1049]
Theme choice does not persist when the web browser session is terminated.

I'm a dark mode user for the website & I get a bit irritated when I have to retoggle the theme every time I visit the site on a different day.

I will be submitting a fix for this in the near future (just need to clean up my local branch).

P.S. Thank you for the awesome website :)

**Comment by ElementUser** [comment]
Added my PR here that addresses this issue: https://github.com/Sendouc/sendou.ink/pull/1050

**Comment by Sendouc** [comment]
I think https://github.com/Sendouc/sendou.ink/commit/b340f32ae38e1487cf73818a631ad27ea12e6b39 fixes it

Can you test when you are able?

**Comment by ElementUser** [comment]
> I think [b340f32](https://github.com/Sendouc/sendou.ink/commit/b340f32ae38e1487cf73818a631ad27ea12e6b39) fixes it
> 
> Can you test when you are able?

@Sendouc I checked out that commit & ran the app locally, I can confirm that your commit fixes the issue!! :)

I will close my PR - thanks again for fixing it! :)
