### ISSUE TITLE
Flicker with combobox

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1053]
https://user-images.githubusercontent.com/38327916/198339006-94f7177e-6b22-4a45-bbf3-33299538923c.mov

**Comment by ElementUser** [comment]
I looked at replicating the issue & found out that it only happens the first time you search for something & do a selection after you've loaded onto that page. If you repeat this without refreshing or leaving the page, this bug won't happen.

**Comment by ElementUser** [comment]
In `Combobox.tsx`, if I set `initialValue={undefined}`, I cannot replicate the issue anymore

**Comment by ElementUser** [comment]
Hmm, nvm on some of that - my PC performance is too good, so that explains why I seem inconsistent on seeing this issue.

It is more prominent on my phone (since it has less computing power than my main pc)

**Comment by ElementUser** [comment]
Okay, I found an actual solution (though probably not the one you want): forcibly preventing reloads in `analyzer.tsx` actually works! I can no longer replicate the original bug if I add this line to the file:

`export const unstable_shouldReload = () => false;`

Reference: https://remix.run/docs/en/v1/api/conventions#never-reloading-the-root

I am sure there is a better way to resolve this though, but leaving this here for your info

**Comment by ElementUser** [comment]
@Sendouc I got a viable solution in this PR: https://github.com/Sendouc/sendou.ink/pull/1131

I explain everything in detail there - hopefully that helps!
