### ISSUE TITLE
Relocate AP selector

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1060]
![image](https://user-images.githubusercontent.com/38327916/198737633-68745632-e60a-4350-b22e-1c0434a34313.png)

There is like a free slot for it on top of the object icons.

<img width="873" alt="Screenshot 2022-10-29 at 14 49 53" src="https://user-images.githubusercontent.com/38327916/198829835-a2fdddac-d231-4d1c-8c8a-ba2e93b8e0e9.png">

Bonus: also show what objectives are affected by which ability when it's toggled. This could be done by showing the corresponding ability icon next to object icon when active.

**Comment by CardBoardBoss** [comment]
![Illustration](https://user-images.githubusercontent.com/15989539/204644948-383d044c-be52-4401-9332-6190417d2a4c.png)
Hey I started working on this, how does it look so far to you?

**Comment by Sendouc** [comment]
Looks good 👍

**Comment by Sendouc** [comment]
Closed with https://github.com/Sendouc/sendou.ink/commit/60b1ca9e261322c1c09458f05b276f4ec0163fd8
