### ISSUE TITLE
Theme selector: system theme

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1061]
Currently it's just dark or light. Would be nice to have 3rd option for system theme (so using your OS preference so when you change it in OS it also reactively updates the site). But then it should not be a toggle but open a little menu popup instead.

**Comment by remmycat** [comment]
Gonna try to implement this :)
I would probably call the third variant "Auto" and implementation-wise make it unset the cookie if there is one.

**Comment by Sendouc** [comment]
Sounds like a plan!

**Comment by remmycat** [comment]
This was implemented with #1083
