### ISSUE TITLE
If user has only 1 result, don't show the Set highlights section

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1068]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/38327916/198830317-199904d0-10e7-487d-afd9-0cc88ab71bb9.png">

There is not really any benefit in doing so if you only have 1 result.

**Comment by ElementUser** [comment]
Made a PR this one since it was quick: https://github.com/Sendouc/sendou.ink/pull/1071
