### ISSUE TITLE
Hovering over a main weapon on a BuildCard shows the Weapon ID

### ISSUE THREAD

**Issue by ElementUser** [Sendouc/sendou.ink#1074]
Hovering over a main weapon on a BuildCard shows the Weapon ID

![image](https://user-images.githubusercontent.com/15804376/198847501-5a56fd24-7337-4544-801c-763ada2b9e60.png)

**Comment by Sendouc** [comment]
Nice to make an issue :) Coincidentally I just fixed it locally like 10 minutes ago... pushing soon.
