### ISSUE TITLE
Show how many chunks to make build

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1093]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/38327916/200047570-196c94a5-9e54-44cc-9577-200c42095b38.png">

**Comment by ElementUser** [comment]
This didn't have a `help wanted` tag on it, but this one didn't look too difficult to do, so I went ahead & implemented the requested feature in this PR: https://github.com/Sendouc/sendou.ink/pull/1120
