### ISSUE TITLE
Upgrade to Node.js 18

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1106]
It's LTS now

**Comment by ElementUser** [comment]
Hey @Sendouc , not sure if this helps, but I tried manually changing the version in `nvmrc` to `v18.12.0` (LTS version of Node.js 18).

I get the usual error where the `better-sqlite3`  module was compiled with a different Node.js version, so as usual I just re-ran `npm install` and re-ran the application on localhost. Works like a charm for me without any further changes :)
