### ISSUE TITLE
Feature Progress Tab

### ISSUE THREAD

**Issue by Yola-cola** [Sendouc/sendou.ink#1111]
The Translation Progress Tab you recently added is really nice. I'm wonder if you can do a similar thing with the website features. Like a simple task list of all the elements from the Splatoon 2 version your need to carry over to the Splatoon 3 one.

**Comment by Sendouc** [comment]
Hey just saying same thing as on Discord but I don't know if having a roadmap in this project would be truthful since it's changing so much.
