### ISSUE TITLE
Calendar week links widths not symmetric

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1117]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/38327916/201196100-2e67ba6e-bafa-4ee8-ba29-60a101b00fb4.png">

The first one from left and last are different width. Should be symmetrical so they are same width and then second from left and second last are same width etc.

**Comment by ElementUser** [comment]
Ah dang, didn't realize my previous fix didn't end up fixing this issue - I might find time to take a look at this again soon (hopefully this week)

**Comment by Sendouc** [comment]
I will probably just end up reworking the whole page to something a bit different down the line.
