### ISSUE TITLE
Using weapon combobox zooms in on iOS and stays zoomed after submit

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1129]
This issue is at least on iOS

1) Go to build analyzer
2) Click weapon input
3) Notice screen zooms in
4) Enter and select some weapon
5) Notice screen stays zoomed in.

Expected would be that in 5) we would return back to 100% zoom level and not stay zoomed in.

**Comment by ElementUser** [comment]
I tested it on my brother's iPad and I don't seem to encounter this issue (tested in both Safari and Chrome). 

Maybe the issue only occurs on iOS phones?

**Comment by Sendouc** [comment]
I think so yeah.

**Comment by remmycat** [comment]
In general I wouldn't interfere too much with the browser default handling of this. Safari on iOS generally doesn't zoom back out as far as I can tell.

Theoretically there might be a way to restore original zoom by shortly setting a meta tag for the viewport with `maximum-scale=1` and then removing it again to prevent the other issues this causes on e.g. android.

But it seems really hacky and would probably not be smooth in any way, especially with smaller inputs where the browser zoomed in a lot.

Possible options I see:
- Have the input have a font-size of at least 16px by default (this completely deactivates the auto zoom-in)
- Tweak the CSS to have the input fill the whole width of the page somehow (unclear if this is possible   without changing the design, depends on size calculation used for zooming)

Personally I'd probably favour the first approach, it seems sensible to me to have a bigger font size if we do not want the client to zoom in. But I haven't checked yet how it looks.

**Comment by Sendouc** [comment]
Ok interesting but makes sense. Learned something new. I think we are doing too small font size on average so maybe a bigger overhaul is needed. Maybe for this ticket just increasing it for analyzer only to 16px would be the way to go.
