### ISSUE TITLE
Clicking on background image should make weapon image lose focus

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1158]
Currently double click is needed. It works correctly before you add the background image.

https://user-images.githubusercontent.com/38327916/203584990-e7374707-0014-4402-a14a-e1b4673f8d96.mov

**Comment by ElementUser** [comment]
I notice that hovering the cursor over the background image still marks it as "selected" (and thus, it still grabs the focus of the cursor), despite it being locked. I'll look through the TLDraw documentation to see if there's a way to make it not able to grab the focus of the cursor.

**Comment by ElementUser** [comment]
So I spent some time & I don't think they have an API method to make the background image ignore your cursor, so to speak.

I noticed that you can still right-click the background image to unlock it if you really wanted to.

**Comment by Sendouc** [comment]
Yeah it's not a problem if they unlock it with a right click. The problem is just the UX of when you want to lose focus. Currently it doesn't really work how you'd expect. Meaning if in any drawing program you click the background you expect to lose focus of the current thing.
