### ISSUE TITLE
Initial install bugs

### ISSUE THREAD

**Issue by kjhf** [Sendouc/sendou.ink#116]
- Readme has incorrect directory -- assuming `cd frontend-react` 
- 1 vulnerability, fixed using `npm audit fix`
- npm ERR! missing script: watch, not fixed after trying `npm install watch`

**Comment by Sendouc** [comment]
My bad letting it get outdated. Updated it to something that could make it a bit easier to install the project.

I do want to make it easier in the future to spin up the project. Currently there are some a bit inconvenient parts like having to manage two DB connections (currently migration away from MongoDB).

Either way closing this for now. Feel free to make a new issue or DM me on Discord/Twitter if you have more problems with it.
