### ISSUE TITLE
User Page: Build Cards Container Box takes up too much width when vertical scrollbar is present

### ISSUE THREAD

**Issue by EliteSoba** [Sendouc/sendou.ink#117]
Seems to be caused by 2e257875ea10593de5ebc602c041dbd8780498a3 which addressed #109.

Line 95 of `BuildTab.tsx` sets the available width for build tabs to be `100vw`, but the full `100vw` is rarely available due to the presence of the vertical scrollbar. This causes a horizontal scrollbar to appear.

Tested on Vivaldi, Chrome, Firefox, and Edge on desktop. Can provide more specific build numbers if desired.

**Comment by Sendouc** [comment]
Thanks for the detailed report. Seems like it was an issue that wouldn't appear on Mac. I think it's good now.
