### ISSUE TITLE
Clear weapon inputbox after selecting weapon / before next selection

### ISSUE THREAD

**Issue by DoubleCookies** [Sendouc/sendou.ink#1193]
When choosing a weapon, the input field is not automatically cleared.

**Comment by DoubleCookies** [comment]
Did not find a good solution - the field is not completely cleared

**Comment by ElementUser** [comment]
Honestly I like the way it currently functions =)

**Comment by DoubleCookies** [comment]
Well, _"it just works"_.
I thought that clearing it will be better but it's more difficult than I expected.

**Comment by ElementUser** [comment]
> Well, _"it just works"_. I thought that clearing it will be better but it's more difficult than I expected. Maybe it's not an issue at all?

I don't think it's an issue at all, personally

**Comment by Sendouc** [comment]
If I understand this issue correctly I agree that it's not really a problem. But if we find some cases where it could be awkward UX or cause real problems lets revisit.
