### ISSUE TITLE
Free agent page

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1234]
Like the old site but also for teams to look for members, looking for people to play with (not just team) or even Salmon Run mates or something.

Show time zones + time difference to user time zone.

**Comment by guigas7** [comment]
Found this in challengermode.com and i think it's a really good template to base it on. I think the best thing this feature can offer is the filtering so you don't have to read through dozens of free agents / teams that don't fit what your're looking for, so to me, the more filters, the better.

![image](https://github.com/Sendouc/sendou.ink/assets/11247506/20e02efe-569f-4cd3-ab01-c22c38092984)

https://www.challengermode.com/valorant/team-finder

Everything in here is really useful, like how old is the fa post, visual icons for roles / weapons, actual post hidden with the "show more" button, and you can even add the player's data once you launch the tournament feature.
