### ISSUE TITLE
No spacing between checkboxes/radios

### ISSUE THREAD

**Issue by lolametro** [Sendouc/sendou.ink#127]
![image](https://user-images.githubusercontent.com/13728127/95108510-a48b7580-073b-11eb-9af0-43e26fcb5036.png)

There's no spacing/margin between the checkboxes/radio buttons on the "Create free agent post" modal.
Adding `spacing={5}` to the `CheckboxGroup`/`RadioGroup` should fix it (although the default value should be 8px according to Chakra UI docs, so I don't know why it's not applied here).

**Comment by Sendouc** [comment]
Thanks for the report! Yeah seems like they deprecated some props in the 1.0 release of the UI library I'm using changing the default behaviour a bit.
