### ISSUE TITLE
Copyright line in footer overlaps the left nav bar (and occupies too much horizontal space in general)

### ISSUE THREAD

**Issue by ElementUser** [Sendouc/sendou.ink#1276]
![image](https://user-images.githubusercontent.com/15804376/221364697-624a8cde-40b7-45a9-a320-cfad95a91968.png)

Easy fix should be to split this into 2 lines

**Comment by Sendouc** [comment]
Nice catch! I have max-width on the patrons list shown in your screenshot but seems like I forgot it from the copyright section.

**Comment by ElementUser** [comment]
Ah, I forgot to mention that for some reason, I use 175% zoom on the site - either way I'll open a PR :) ty Sendou
