### ISSUE TITLE
Side nav icons difficult to discern without labels

### ISSUE THREAD

**Issue by justintricate** [Sendouc/sendou.ink#1289]
![image](https://user-images.githubusercontent.com/47122570/222382290-065b79d0-f8ca-42f4-850d-0b0f206b24f5.png)

It can be difficult at a glance to tell what each icon means at a glance. Could use built in "title" on the <Image> or a more stylish tooltip text. Or neither :P your call, Sendou-- I am submitting a PR with the flyout tooltip text created and styled if you wish!

**Comment by Sendouc** [comment]
Unfortunately had to revert the PR as it was prevent links from being clicked. Saw this issue on badges page but probably there would have been issues elsewhere as well. I think maybe a different approach would be needed.

**Comment by justintricate** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role

MDN talks about using tooltips, which we could implement for sure. It does beg the question-- if the information is important enough for a tooltip, isn't it important enough to always be visible?

Perhaps the icons being re-designed to show their labels is the _actual_ answer, rather than an aesthetic workaround? Worth considering...

**Comment by Sendouc** [comment]
Yeah it's an interesting question! I guess my philosophy was that since they are clearly defined on the front page the side nav is supposed to be little more than "quick access" so lacking some clarity is ok. Although it could be true that when the number of them grow the current solution will soon become obsolete anyway.

**Comment by Sendouc** [comment]
Eventually will be fixed by the whole side nav being gone.
