### ISSUE TITLE
Sidenav hidden behind header when screen is short

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1305]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/38327916/224121408-8ff09b9a-45fa-456b-9acb-58e1dc1d475e.png">

You can't scroll up to see the full nav. Probably some padding is missing?

**Comment by ElementUser** [comment]
As a side note, this also breaks with increased zoom levels on a a 24 inch 1080p screen

**Comment by pm-wobbuffet** [comment]
`@media screen and (max-height: 900px) {
    .layout__side-nav {
        top: 3rem;
        justify-content: flex-start;
    }
}`
Adds a little vertical gap to the positioning at shorter viewports, along with un vertical-centering the icons, so the top ones don't get pushed off.
![image](https://user-images.githubusercontent.com/6683213/232264194-8bb70718-1d0e-4874-84c5-f7457b11cc28.png)
