### ISSUE TITLE
directory/menu doesn't change to selected language

### ISSUE THREAD

**Issue by cYuza** [Sendouc/sendou.ink#131]
![image](https://user-images.githubusercontent.com/59847833/95656950-e0df1d00-0b11-11eb-99cc-f2e438fa7331.png)

**Comment by Sendouc** [comment]
It just didn't get translated to German yet. You can see the progress of translation here: https://sendou.ink/translate

**Comment by Walavouchey** [comment]
These have been translated (under "navigation") and the issue exists for the other languages as well.

**Comment by Sendouc** [comment]
Ah true. Had to add one new translation label but it's fixed now.
