### ISSUE TITLE
Filter build stats

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1331]
Checkbox to only show +1,+2,+3 and top 500.

![image](https://user-images.githubusercontent.com/38327916/230761432-3d53f280-7633-49ae-ba1b-887cbe1175a2.png)

**Comment by Cerxi** [comment]
Can I extend the recommendation to cover the "popular builds" tab as well? Casual players copying whatever build they see first are going to skew those stats pretty heavily otherwise.
