### ISSUE TITLE
X-Rank Leaderboards page missing Octobrush information

### ISSUE THREAD

**Issue by SporeCloud** [Sendouc/sendou.ink#134]
On the X Rank Leaderboards page there is no option to select leaderboards for Octobrush, Octobrush Nouveau and Kensa Octobrush, it skips from Permanent Inkbrush to Classic Squiffer in the list.

**Comment by Sendouc** [comment]
Not a fan of Octobrush but that's going too far. Will fix. Thanks for the report.
