### ISSUE TITLE
IGN discriminators can have more than 4 digits

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1355]
![image](https://user-images.githubusercontent.com/38327916/234041897-332b2b6c-a792-47c7-9b71-7343403c040e.png)

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/38327916/234041935-6d55e3c7-9202-45c8-a3f1-ea24318d2488.png">

This seems like a bug on Nintendo's side so maybe the play is to wait for them to fix it? If it's intentional and seems to stay then need to adjust the validators on the user profile.

**Comment by cesaregarza** [comment]
This is not a bug, this is the way they've decided to implement the discriminator. I can't find it the exact github issue, but this is known.
