### ISSUE TITLE
Squidternship Program

### ISSUE THREAD

**Issue by eholland173** [Sendouc/sendou.ink#1361]
Develop 'internship' program for low-level/beginning players to intern with top-level competitive teams or tournament organizers to develop robust video data library, aid in tournament data collection and facilitation, and aid in improving social media presence. 

When thinking about professional sports, one of the ways that people break into analytics, coaching, and management careers is through video editing and working the film room. Cutting up film is a labor-intensive process that a team delegates out to their analytics department and, consequently, interns. Given that Splatoon is not a multi-billion dollar a year industry, Splatoon competitive teams barely have enough time for team practice, individual practice, etc. to go in and do the deepest of video archiving and collecting specific portions of data to analyze what went wrong in the same way someone might have in sports. Moreover, top teams don't really have the largest footprint on social media, youtube, etc. because, again, why do that when there is time for practice. 

With that, the benefits of a Squidternship has the capacity to improve the entire scene on multiple levels. 

For the top competitive teams:

They get a Squidtern to hunt down film footage they are looking for from their matches, archive the videos and clips into a usable, standardized data structure, someone to handle their social media postings, and others issues that teams just need another set of hands to do, maybe art design or something. This will allow competitive teams to do more match analysis and have more productive film and strategy sessions which is likely the limiting factor for these teams to advance in their division, assuming they are playing at a sufficiently high technical skill level. This will also allow the teams to be elevated, and the players themselves, instead of content creators and the weapons being the stars of show. So much conversation is about crab and machine nerfs and the dominance of 2x crab lineups and how that's "boring" to watch instead of, "I like how this player and this team uses their double crab double machine line-up, they consistently get better value out their specials when defending pushes relative to this other team." Squidterns can help push and promote the teams to have them start taking up more space in the YouTube algorhithm, which could help everyone get a little extra cash for going to tourneys or getting kick-ass shirts. 

Squidterns: they get a resume' builder to say that they ran a video archive and social media for a team which can help build out a resume' for folks. Additionally, they get to learn and discuss the game in a far more intimate setting with folks that are likely much better than them, so they can learn how upper division players discuss the game which will improve their game much, much faster, than whatever they are doing. 

The community at large: 

This would significantly elevate the discussion about the game, start putting the players and teams that are competing at the highest levels out there a lot more, and let the play drive the discussion instead of tier lists and what is wrong with the game. By raising the floor of competition and allowing lower division/beginning players access to upper div players, it could help push the Western scene by getting more people thinking and talking about the game in a productive way. 

How this would work in the real world: hell, this would be a massive organizational undertaking that would involve the creation of some sort of ethics and standards of treatment, advertising, etc. plus the managing of the all the video archives, etc. but I think the payoff would be pretty solid. Off the top, I bet Gem at Squid School would be remotely intrigued though I don't know him so who the hell knows.

**Comment by Sendouc** [comment]
I definitely see the idea behind this and see the value as well. However probably currently I don't have time to facilitate something like this.
