### ISSUE TITLE
Thematic analysis of competitive player interview data

### ISSUE THREAD

**Issue by eholland173** [Sendouc/sendou.ink#1363]
Create semi-structured interview to capture relevant data from top competitive teams, players on:

successful habits/routines
how they think about the game
team dynamics
what it takes to win
hours dedicated, etc. 

Or other data concerning how top players feel about the conversation about the game, the state of competitive play, eSports, etc. 

Conduct 10-20 interviews, or maybe expand to focus-group discussions with folks across different teams and analyze via thematic analysis using qualitative analytics software such as Dedoose, Atlas.ti, or even something like Zotero. Find themes, create network diagram, flowchart, sankey, or whatever visualizing results along with notable quotes and researcher analysis. Depending on the quality of the work and if a journal exists, this could get published as legitimate research.

**Comment by Sendouc** [comment]
I think this would be interesting and I'd be happy to read such an analysis but it is out of scope for this project at this point in time.
