### ISSUE TITLE
use discord "display name" instead of "username"

### ISSUE THREAD

**Issue by m4rch3n1ng** [Sendouc/sendou.ink#1391]
with the new discord username system i think it would be best not to display the `"username"` on the profile page (in part because of privacy concerns and in part because it's kinda annoying to have like `_.-` and numbers in there if your actual name was already taken) and instead use the newly added discord `"display name"`, and use the `"username"` / legacy system as a fallback option only.  
you could additionally add an option to *also* show the new `"username"` in a seperate field, if, for example, you want people to be able to friend request / dm you there.

**Comment by Sendouc** [comment]
Yeah right what I did now is just a stopgap solution as the Discord API change was quite sudden in my opinion. For future I will have completely separate "sendou.ink display name" but I need to figure out exactly how that should work. Probably using "custom url" as custom identifier but of course that is not mandatory currently so yeah some things need to be figured out.

> you could additionally add an option to also show the new "username" in a seperate field, if, for example, you want people to be able to friend request / dm you there.

Yeah I think that's a solid idea to have it showing as opt-out.

**Comment by m4rch3n1ng** [comment]
i think honestly the global discord display name would be good enough (imo that's like the intended use of that feature), at least if you are fine with having non-unique names, but in the long run having the option to set a sendou.ink-only display name would be a nice-to-have.
