### ISSUE TITLE
Builds when filtering errors out in Safari

### ISSUE THREAD

**Issue by AdamW19** [Sendouc/sendou.ink#143]
**System:** macOS 10.14.6
**Browser:** Safari 12.1.2 (14607.3.9)
**Extensions:** PiPer 1.0.4, RES 5.2.2, Tampermonkey 4.8, uBlock Origin 1.16.0
**Tampermonkey add-ons:** Anti-Adblock Killer 10.0, Facebook Purity 29.5.0-11thJun2020

**How to replicate bug:** Visit sendou.ink, Builds --> Browser, enter Splattershot Jr, filter by "Tenacity".

**Error:** 

> An error occurred: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

> If you let me know on GitHub, Discord or Twitter I can do my best to get the problem fixed!

> ns@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:514868
ga@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:486673
ga@[native code]
https://sendou.ink/static/js/14.c7bdf522.chunk.js:1:51982
uu@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:507512
Ss@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:526637
unstable_runWithPriority@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:544962
us@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:518114
us@[native code]
https://sendou.ink/static/js/11.e413b52a.chunk.js:2:469561
unstable_runWithPriority@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:544962
Xo@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:469507
Yo@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:469442
D@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:538728
Yt@https://sendou.ink/static/js/11.e413b52a.chunk.js:2:446712
Yt@[native code]

**Full error message is:** `Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

Bug doesn't exist on Firefox 82.0.2 or Chrome 86.0.4240.183. Bug is repeatable on Safari, even with all extensions disabled.

**Comment by Sendouc** [comment]
Thanks I was able to reproduce this.
