### ISSUE TITLE
Build Analyzer - Incorrect/Missing Special Power Up effects

### ISSUE THREAD

**Issue by Filuz** [Sendouc/sendou.ink#1434]
Inkjet and Reefslider uses their "SplashAroundPaintRadius" (the tiny droplets generated by explosions) instead of the proper "PaintRadius" values. Commenting out line 470 through 473 in `create-analyzer-json.ts` fixes this issue but...

This leads to a second issue, as Inkjet and Tenta Missiles are missing the SpecUpType line for PaintRadius in their parameters (they're there in the mission files tho), which causes the script to skip those. 

The simplest way to fix it is to manually add the missing line, though this would require to do so every balance update. Another way might be to hardcode the values similarly to damage (but I do not know how to do that, sorry!)

**Comment by Sendouc** [comment]
Yeah you seem to be right. Thanks for reporting!
