### ISSUE TITLE
Adjust skill calculation

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1475]
- Shouldn't be able to lose skill from winning
- Gain less if playing with lower level mates

**Comment by cesaregarza** [comment]
Adding a floor to winrate is going to lead to problems down the line as more playtime will statistically grant more points. Maybe track true points under the hood and have visible points that track closely to true points but don’t go down when winning?

Alternatively (but uhhh, not a good solution for the short run) implementing a different MMR algorithm like Elo-MMR. Problem is it’s too new which means it has few implementations, and the white paper isn’t a pushover.
