### ISSUE TITLE
UI Issues - Arrows on the wrong side when selecting Hebrew

### ISSUE THREAD

**Issue by shachar700** [Sendouc/sendou.ink#1513]
In art at the bottom:
![Screenshot_88](https://github.com/Sendouc/sendou.ink/assets/48739719/61bed184-7162-40a5-8c9d-f6e153ca877c)

In menus such as map lists, or in max/min menu of DMG calc:
![Screenshot_89](https://github.com/Sendouc/sendou.ink/assets/48739719/f3ed9875-6315-4f70-85b0-b85b71415108)

as well as in map planner, map lists. 

The toggle in art for open submissions is also a bit off in its location.

**Comment by duplicatedframe** [comment]
I believe this is solved simply by drawing the left arrow on the right button and vice-versa if the user language's direction is `rtl`, as we'd still expect the behavior of the buttons and pagination dots to reverse alongside the language.

Working on implementing and will create a PR shortly.
