### ISSUE TITLE
Tournament embed logo preview to work on Twitter

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1741]
<img width="594" alt="image" src="https://github.com/Sendouc/sendou.ink/assets/38327916/c5ba48b2-92c1-444b-84a7-3458a19aa678">

What would it take to get the logo to show up here as well? Discord embed works great

**Comment by KaiserOfNone** [comment]
I think we need to add some twitter specific tags to tell it how to render it maybe [1], I'll experiment with it later

[1]: https://developer.x.com/en/docs/twitter-for-websites/cards/guides/getting-started
