### ISSUE TITLE
Add French (NoA localization) as a language

### ISSUE THREAD

**Issue by ximk** [Sendouc/sendou.ink#1764]
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/851974d5-1b3d-40a7-8cbb-19c2e24c5f93)

Example (with the Zebrafish Hi-Tops):
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/ea400121-cb3c-48fc-b25d-9934c702efd9)

The plan here should probably be to copy the French translations already present on the site and add it as a new language, and then edit the files `game-misc.json`, `gear.json`, and `weapons.json` to reflect the NoA localizations.

I've translated `game-misc.json` already, I'll just need the auto-generated files for the NoA localization. I'll submit what I have in a PR shortly.

**Comment by Sendouc** [comment]
Let me know if you can't figure out how the auto-generation works. Tbh I kinda forgot myself but I can find out

**Comment by ximk** [comment]
Got it to work! :)

Later, I'll PR a change to the README with a more detailed instructions for the monthly update.
