### ISSUE TITLE
Allow looking for individual coaching

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1769]
New LFG post type

![image](https://github.com/Sendouc/sendou.ink/assets/38327916/09c2833f-b16e-4656-b664-c49ac687d76c)
https://discord.com/channels/299182152161951744/1251247392603246814/1251247392603246814

**Comment by ximk** [comment]
Would just using the current "looking for team" template be enough? I can PR this if so:
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/7008e44c-cd61-4dba-bbc4-02114acee1f8)
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/06507806-850a-4489-98ee-eaee23d26990)

**Comment by Sendouc** [comment]
Yes I think that works
