### ISSUE TITLE
Get rid of Prettier dependency

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1773]
We still use Prettier in `check-translations-json.ts` to format the generated Markdown file. Could that be migrated to Biome or removed via some other method? This would allows us to completely remove Prettier dependency.

**Comment by ElementUser** [comment]
@Sendouc so I spent quite a lot of time on this one with the biome suggestion & was wondering why it just won't work no matter what...

After I turned on verbose debugging with the `biome format` command, that referred me to the official documentation for language support. Unfortunately, biome does not support formatting Markdown (.md) files, and this is exactly what we're using it for in that `check-translations-json.ts` file.
- Reference: https://biomejs.dev/internals/language-support/

So sadly, we cannot use biome for this & looks like `prettier` is still a solid option for us
