### ISSUE TITLE
Serbia flag invisible on profile

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1777]
<img width="219" alt="image" src="https://github.com/Sendouc/sendou.ink/assets/38327916/9ca4b0e8-2dc9-4685-b704-c26c90df0170">

<img width="369" alt="image" src="https://github.com/Sendouc/sendou.ink/assets/38327916/217a59b4-e87f-4e29-9a64-c5dc218860d3">

Why?

https://discord.com/channels/299182152161951744/1255085043664027689

**Comment by ximk** [comment]
It looks like the Serbian flag was never added in `.flags.css`, maybe that's the issue?

![image](https://github.com/Sendouc/sendou.ink/assets/104683822/5f5aa250-d738-4236-a6c3-afe33de707d7)

**Comment by Sendouc** [comment]
Hmm is it possible to check if it's just Serbia or are there other missing from countries-list NPM package? Interesting though

**Comment by ximk** [comment]
I found South Sudan was also missing it's flag by just clicking through countries and seeing if their flags appear on the user page. I don't know if there's a better way to check outside of going through the two-letter codes and seeing if they appear in `flags.css`.

**Comment by Sendouc** [comment]
I think maybe some small script might be the most fool proof way.

**Comment by ximk** [comment]
Just confirmed that is the issue. I added it myself locally, and this is the result:
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/82e3d2e9-ed33-4be8-9ece-c2d0e2349ebe)

**Comment by ximk** [comment]
Should I just PR the fix with the Serbian flag, or do you want to wait to find them all (and add them) before PRing?

**Comment by Sendouc** [comment]
Decided to just fix the Serbia case for now and if there is further user feedback then act on that.
