### ISSUE TITLE
Add a report button to user and team profiles

### ISSUE THREAD

**Issue by csdepop100** [Sendouc/sendou.ink#1781]
Hey I noticed a profile on sendou.ink with racist hate speech in their bio and their team bio

![Screenshot 2024-06-27 151036 - annon](https://github.com/Sendouc/sendou.ink/assets/49524272/a4b4689e-80f5-429a-8763-20293c5f23fd)

![image](https://github.com/Sendouc/sendou.ink/assets/49524272/528bde11-f219-4fec-bf32-be5e8807c29a)

I couldn't find an intuitive way to make moderators aware of profiles like that, I think it would be a good way to show support for victims of hate speech in our community given recent events.
If any of your mods wants to discuss this case in detail contact me on discord: mostlydennis

Thanks a lot

**Comment by Sendouc** [comment]
Hey thanks for letting me know, dealt with that user. 

What kind of advantages would a built-in system have over our current approach on Discord? Or is it a lack of documentation how to do it? I guess I could see some value with a built-in system like that as well but I'm wondering if there is a possibility that then there is two similar ways to do the same thing which could be worse for the user and the moderator.

**Comment by hfcRed** [comment]
## Pros
* Everything in one place, easy overview
* Keeps drama away from the public/discord
* Can sort by how many reports each person in the list has, easier to spot really bad actors

## Cons
* Anonymous reporting leads to report spam as ppl will start reporting for the dumbest reason, making it harder to find legitimate reports
* Person that made the report gets no feedback of ongoing situation or resolution

**Comment by csdepop100** [comment]
Thanks for the quick reply! I think it's a lack of documentation. Any kind of on-site report hint or feature could be very helpful really.
Because the friends who brought this to my attention had no clue what to do with this.

**Comment by csdepop100** [comment]
I think even a little hint on hover like this quick and dirty mock-up could do the trick

![image](https://github.com/Sendouc/sendou.ink/assets/49524272/902a90e2-547c-4bcf-baed-c39703b236bc)
