### ISSUE TITLE
Tournament description page sometimes shows modes that aren't in the map pool

### ISSUE THREAD

**Issue by ximk** [Sendouc/sendou.ink#1782]
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/d1a04c17-9ffd-4db9-acd4-49fcd7734be5)
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/bc6bb652-a388-46fb-9a69-291ba3f8b9a6)

**Comment by ximk** [comment]
If I'm reading the code correctly, currently we only use the "one mode display" when `Prepicked by teams - [Mode] only` is used. When those options are not picked, we should probably base it off of the map pool selections instead (if possible). That way, if you hosted a SZ, TC, and CB tournament, those 3 would show at the top.

There's also no way currently to show TW is in the map pool at the top either, and my suggestion would fix that as well.

**Comment by Sendouc** [comment]
Yeah I think that sounds reasonable.

Prepicked by teams -> should come from the map list picking style
Picked by TO -> infer from map pool
