### ISSUE TITLE
Adjust weapon pool build sorting to include alt kits/skins

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1794]
- Include variants (alt skins, alt kits) in the sorting
- If the weapon pool contains a variant, sort that first

examples

Weapon pool = Luna Blaster, Splat Roller
Currently sorts first Luna then Splat Roller
Should be = Luna, Luna Neo, Roller, Krak-on roller, order replica

---

Weapon pool = Luna Blaster Neo, Luna Blaster, Splat Roller
Currently sorts first Luna Blaster Neo then Luna then Splat Roller
Should be = Luna Neo, Luna, Roller, Krak-on roller, order replica

-

It would be also nice to include unit tests

**Comment by rikipls** [comment]
Working on this
