### ISSUE TITLE
Memory leak after switch to Bun

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1833]
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/2f97c76f-9c44-4aa6-81e9-ab192a88cd36">

Diagnose what is leaking with https://bun.sh/docs/project/benchmarking#measuring-memory-usage

Possible suspect is LRU-cache, at least saw one GitHub issue related to that library but need to verify.

**Comment by Sendouc** [comment]
Tracking https://github.com/oven-sh/bun/issues/13362

**Comment by Jarred-Sumner** [comment]
sorry about this

**Comment by Sendouc** [comment]
> sorry about this

Nothing to be sorry about!

I had success with running Bun on [a smaller service](https://github.com/Sendouc/skalop) so wanted to see if it could work here as well. Seems like still going to be using Node.js for now but the tool chain improvements are nice too. Then hoping that later could give another shot at the Bun runtime as well.
