### ISSUE TITLE
Unknown strategy "discord"

### ISSUE THREAD

**Issue by AToska21** [Sendouc/sendou.ink#1838]
I keep getting this issue when trying to run this locally to test something.

I can't login at all, here's the error:
```node
error: Strategy discord not found.
      at authenticate (/root/sendou.ink/node_modules/remix-auth/build/authenticator.js:67:19)
      at unknown:50:65
      at logInAction (unknown:45:28)
      at /root/sendou.ink/node_modules/@remix-run/server-runtime/dist/data.js:67:17
      at callRouteAction (/root/sendou.ink/node_modules/@remix-run/server-runtime/dist/data.js:58:4)
      at /root/sendou.ink/node_modules/@remix-run/server-runtime/dist/routes.js:62:69
      at actualHandler (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4671:14)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4683:27
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4681:37
      at runHandler (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4692:11)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4748:22
      at callLoaderOrAction (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4656:35)
      at resolve (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4632:29)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4614:46
      at map (unknown:1:11)
      at defaultDataStrategy (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4614:35)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4623:23
      at callDataStrategyImpl (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4616:37)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4111:25
      at callDataStrategy (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:4110:35)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3970:27
      at submit (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3954:25)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3928:28
      at queryImpl (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3924:28)
      at /root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3897:24
      at queryRoute (/root/sendou.ink/node_modules/@remix-run/router/dist/router.cjs.js:3864:29)
      at /root/sendou.ink/node_modules/@remix-run/server-runtime/dist/server.js:388:40
      at handleResourceRequest (/root/sendou.ink/node_modules/@remix-run/server-runtime/dist/server.js:383:38)
      at /root/sendou.ink/node_modules/@remix-run/server-runtime/dist/server.js:336:9
      at requestHandler (/root/sendou.ink/node_modules/@remix-run/server-runtime/dist/server.js:218:37)
      at /root/sendou.ink/node_modules/@remix-run/dev/dist/vite/plugin.js:1032:222
      at processTicksAndRejections (unknown:12:39)
```

**Comment by hfcRed** [comment]
That's because it's trying to use the env variable BASE_URL which is set to an empty string.

You can fix this by either adding the BASE_URL with the value ``https://discord.com/api/oauth2/authorize`` to your env file, or by modifying the function ``authEnvVars`` in ``DiscordStrategy.server.ts`` to return that value as the BASE_URL

**Comment by AToska21** [comment]
alright, ill try this

**Comment by AToska21** [comment]
> https://discord.com/api/oauth2/authorize

nope, still throws the same error.

**Comment by hfcRed** [comment]
Did you change anything, did you follow the exact steps from the readme, when was the last time you pulled the repo

**Comment by AToska21** [comment]
> Did you change anything, did you follow the exact steps from the readme, when was the last time you pulled the repo

I just repulled the repo today, I followed the exact steps. I'll run `git reset` just to be sure.

**Comment by AToska21** [comment]
Same error. I'll try spinning up a fresh VM with only the requirements needed for node and bun.

**Comment by AToska21** [comment]
Nothing, still the same.

**Comment by AToska21** [comment]
Any way to solve this?

**Comment by Phil-hacker** [comment]
you could try setting the enviroment variable `LOGIN_DISABLED `to `true`, that disables login and remove the error

**Comment by AToska21** [comment]
> you could try setting the enviroment variable `LOGIN_DISABLED` to `true`, that disables login and remove the error

i mean yeah it works, but the error only happens when i try to login

**Comment by AToska21** [comment]
and also defeats the whole purpose of the system

**Comment by hfcRed** [comment]
do you actually need to be logged in to do what you want to do?

**Comment by AToska21** [comment]
> do you actually need to be logged in to do what you want to do?

yes

**Comment by hfcRed** [comment]
would bypassing the login and impersonating Sendou on the /admin page suit your needs

**Comment by Sendouc** [comment]
Think there is something weird with Vite there. IIRC I had to inline the `DISCORD_AUTH_KEY` constant in the DiscordStrategy.server.ts file or something crazy like that.

**Comment by AToska21** [comment]
> Think there is something weird with Vite there. IIRC I had to inline the `DISCORD_AUTH_KEY` constant in the DiscordStrategy.server.ts file or something crazy like that.

no i think remix-auth isnt picking up the discord auth strategy

**Comment by AToska21** [comment]
> would bypassing the login and impersonating Sendou on the /admin page suit your needs

im testing something w/ discord oauth (unfortunate i got this error lol)

**Comment by AToska21** [comment]
Any updates?

**Comment by AToska21** [comment]
Found a fix, I think? It actually redirects to Discord now.
Replaced authenticator.use(new DiscordStrategy());
with
authenticator.use(new DiscordStrategy(), DISCORD_AUTH_KEY);

**Comment by AToska21** [comment]
okay after trying to login it just closes the connection

**Comment by AToska21** [comment]
nvm that was my issue using https when not supposed to

**Comment by AToska21** [comment]
okay im just not sure what "AUTH_GATEWAY_PROFILE_URL" is.

**Comment by AToska21** [comment]
> Found a fix, I think? It actually redirects to Discord now. Replaced authenticator.use(new DiscordStrategy()); with authenticator.use(new DiscordStrategy(), DISCORD_AUTH_KEY);

after just removing the discord token and profile URLs from .env, it now works!
