### ISSUE TITLE
Replace Twitter links with bsky

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1873]
Replace these

<img width="556" alt="image" src="https://github.com/user-attachments/assets/f128c182-6b04-4b4d-a21c-b23416219679">

<img width="834" alt="image" src="https://github.com/user-attachments/assets/27d1484c-8009-44b1-8d7a-0ebaf0607ce9">

Open question: should we somehow verify the bsky on user profiles or user submitted and accept it's unverified?

+ link in the footer to https://bsky.app/hashtag/sendouink?author=sendou.ink
+ icon to the org social links

**Comment by hfcRed** [comment]
Is this a full replacement or just another link option?

**Comment by hfcRed** [comment]
A neat way you can do automatic verification is if you generate a random 8 digit number and tell the user to add the number to their Bluesky profile description.

The user then pastes their profile link into an input and you can then use the Bluesky API to get the description of the profile and check if it contains the number you generated.
https://docs.bsky.app/docs/api/app-bsky-actor-get-profile

Quick, easy and free.

**Comment by Sendouc** [comment]
Keeping Twitter around for now. Will re-evaluate later.
