### ISSUE TITLE
Get tournament info through API

### ISSUE THREAD

**Issue by La-Rosi** [Sendouc/sendou.ink#1892]
I'm planning on using the API for my tournament. My tournament uses a online web page where It should display a few things, but in order to do so, i'd need to get info from the tournament directly from sendou.ink. 
I'd need to access the name of the tournament, the amount of people playing in the tournament, the team names, and the w/l ratio; but I'm sure that acessing more info could be really helpful!

**Comment by vlee489** [comment]
you need an API key, but the endpoints are documented at https://github.com/Sendouc/sendou.ink/blob/rewrite/app/features/api-public/schema.ts

IPL maintains an unofficial Python lib we use internally at [sendou.opensource.iplabs.work/](https://sendou.opensource.iplabs.work/)
