### ISSUE TITLE
"losses to tied teams" tiebreaker picks non-tied teams

### ISSUE THREAD

**Issue by robbyblum** [Sendouc/sendou.ink#1989]
https://github.com/Sendouc/sendou.ink/blob/d3a825bd5747f057c5fd5cdef21bf3610ec66fe8/app/features/tournament-bracket/core/Bracket.ts#L1391

This line is the condition to find "tied opponents", but it only checks how many wins each team has. This means that it will also catch opponents with the same number of wins, but who didn't finish the bracket.

This shows up in real tournament data. One example: in [December Low Ink,](https://sendou.ink/to/815/brackets?idx=0&group=4328) the team Error 404 (who went 3-3) ended up with a TB value of -1, when they should have had 0. The reason they got the -1 is that they lost to Tidy Tidings, who dropped out of the tournament after round 5, finishing 3-2. They beat the only actual 3-3 team they faced (REWIND!!!). But since the function here only checks how many wins each team has, it thought that Tidy Tidings and Error 404 had the same record.

This also happened to the team ✨ Cooler High ✨ (2-4), because they lost to Asphyxiation, who went 2-3. They should only have a -1 (for losing to Tide Breaker), not a -2.

The simplest solution is just to also check if the teams have the same number of losses, I think.

**Comment by Sendouc** [comment]
Good find! thanks
