### ISSUE TITLE
[API] Add ability to get list of teams in bracket/stage 

### ISSUE THREAD

**Issue by vlee489** [Sendouc/sendou.ink#1999]
This is a request to add an API route when requesting from `api/tournament/{tournament_id}/brackets/{bracket_index}/teams` to return a list of teams similar to [`GetTournamentTeamsResponse`](https://github.com/Sendouc/sendou.ink/blob/16657157bb568b7a9b92284d92848eafbd5516f9/app/features/api-public/schema.ts#L96) but just for the requested bracket. 

This request is due to wanting to create the ability to assign roles to teams in a bracket within discord servers. 
_Currently we need to iterate through `data.match` to get the IDs of the teams in a bracket for the data._

**Comment by Sendouc** [comment]
I might just add it to the `GetTournamentBracketResponse` instead like so:

![image](https://github.com/user-attachments/assets/e608b25d-6cd2-412a-aad6-0020278f2200)

Would that work?

**Comment by vlee489** [comment]
Yes this would also work fine.
