### ISSUE TITLE
[REQ] FA search functionality

### ISSUE THREAD

**Issue by zy-f** [Sendouc/sendou.ink#25]
Just a quality-of-life thing that would be nice to have. LUTI divs, timezones, XP, etc. are all hard to filter by, and it’s hard to search up someone’s username if you want to see their FA post.

**Comment by Sendouc** [comment]
Regarding the points you provided

1) LUTI divs maybe something for future but currently the site has no knowledge of this
2) Timezones - already you can search for region
3) XP not so many people have top 500 placements so might not be the most useful

However searching for invidual user should be easier I agree.

**Comment by zy-f** [comment]
No I completely agree -- I meant that keyword searching through FA post descriptions would be a helpful way to search for these specific criteria without having to make it a specific field to fill out in an FA post.

As an example, just being able to search "div 2" or "xp2500" and having it display anyone whose FA post contains the phrase in the description would be useful.

**Comment by Sendouc** [comment]
> it’s hard to search up someone’s username if you want to see their FA post.

This point was improved. Regarding others I thought about it but it's not something I'm going to implement at this point.
