### ISSUE TITLE
User page: Dividers showing up even with no bio

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#293]
![image](https://user-images.githubusercontent.com/38327916/110756967-84fcf980-8253-11eb-94e9-4cb4ed91954f.png)

**Comment by DoubleCookies** [comment]
This issue is pretty tricky. With empty bio there is only divider before build section (if user have them), but if bio have smth like spaces or invisible separators - code add additional divider before bio. Probably dividers work as intended.

**Comment by Sendouc** [comment]
I think it's still an issue as it just looks off to the user (like maybe bio didn't load or something).

Of course the question is if we should be saving bio even when it only contains empty characters (or maybe it's not a problem?) but a quick fix could be maybe checking if `bio.trim() === ""` and then not rendering the <Divider />.
