### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#321]
Once a commit is pushed or PR opened should ran through a pipeline:

1) Check against ESLint #319
2) Check against Prettier
3) Run Cypress tests

**Comment by rofreg** [comment]
I've used GitHub Actions for this on other projects, and it's been very convenient – and free for public repos, which is great. Cypress even appears to have [its own custom GitHub Action](https://github.com/cypress-io/github-action#basic). Maybe I'll look into this soon!

**Comment by Sendouc** [comment]
Yup sounds great! I'm a fan of GitHub Actions from what I know of it. It's nice to have everything related to the development of this project in one place as much as possible.

If you have any questions about the project you can either just make an issue with the tag question or ask on the [Discord server](https://discord.gg/sendou). I check both actively so should be able to answer quick.
