### ISSUE TITLE
Nav icons have text fallback before loading

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#324]
Only on some browsers like Firefox Android. This is jarring and the fallback should simply be that nothing is displayed.

**Comment by DoubleCookies** [comment]
Probably already done?
[Remove alt from icons to avoid showing txt fallback](https://github.com/Sendouc/sendou.ink/commit/761393ffc31ff70bcada87fd4f4e631f692e7ca2)

**Comment by Sendouc** [comment]
Good catch.
