### ISSUE TITLE
Fix or remove factories

### ISSUE THREAD

**Issue by rofreg** [Sendouc/sendou.ink#335]
Unfortunately my Fishery factories are causing some issues with Prisma! Here's the problem as I currently understand it. If these issues are too complex to figure out, it might make sense to just revert my recent changes and get rid of the factories for now.

—

Fishery factories want to return objects, e.g.:

- `userFactory.build()` -> an unsaved `User` object
- `await userFactory.create()` -> a saved `User` object

Fishery is designed such that `build` and `create` both return objects of the same type `T` (or `Promise<T>`).

However, Prisma doesn't have the concept of an "unsaved `User`". Instead, they use the `UserCreateInput` type to represent data that could be turned into a new `User`. I haven't yet figured out how to make this play nicely with Fishery.

One place this causes problems is the `User#id` column. When making a `User` factory in Fishery, we are required to explicitly define a user's ID before creation (because a `User` object must have an ID). This ID is then saved to Postgres. However, because we are _manually_ specifying that ID (vs. getting it automatically from Postgres), the autoincrementing value on Postgres's `User#id` column does not get incremented. As a result, we can run into uniqueness conflicts:

- Running `npm run seed` creates users with IDs 1-12
- If you then try to create a new user normally (e.g. from the browser), Postgres will automatically assign that `User` a new ID of `1`, because the auto-incrementing column has not been incremented at all yet
- This causes a uniqueness conflict with the previous "user 1" created by `npm run seed`, and the new `User` does not get saved

—

This may be a fundamental incompatibility between Fishery and Prisma (or at least, an incompatibility that requires updates to the Fishery library). I opened https://github.com/thoughtbot/fishery/issues/56 to ask for guidance on this issue. If there was a way for the userFactory to _build_ `UserCreateInput` objects, but _create_ `User` objects, I think we'd be all set, but I'm not sure if that's currently possible in Fishery.

**Comment by Sendouc** [comment]
Overall I'm a fan of the factories approach so I think it's worth the effort to get it working. The alternative would be to revert to whatever I was doing earlier but it's just not very readable, generating data sets is very error prone and it's hard to get good variance to data.

Let's see what happens with the issue you posted but otherwise I can also try to read up on the library to see what the solution could be. At least I have some experience with the way you build up objects to be created later with Prisma.

**Comment by Sendouc** [comment]
I'm working on the tests for the new /calendar page and ran in the problem you described above. Here is how I solved it:

```js
import { Prisma } from "@prisma/client";
import { Factory } from "fishery";
import prisma from "../client";

const TWELVE_HOURS = 43200000;

export default Factory.define<Prisma.CalendarEventCreateManyInput>(
  ({ sequence, onCreate }) => {
    onCreate((event) => {
      return prisma.calendarEvent.create({ data: event });
    });

    const now = new Date();

    return {
      // no id required here
      date: new Date(now.getTime() + sequence * TWELVE_HOURS),
      description: `# Our great event ${sequence}\nCome play`,
      discordInviteUrl: "https://discord.gg/sendou",
      isTournament: true,
      format: "OTHER",
      name: `The Event #${sequence}`,
      posterId: sequence,
      eventUrl: "https://challonge.com",
      tags: [],
    };
  }
);
```

So I use the type of `Prisma.CalendarEventCreateManyInput` not `Prisma.CalendarEventCreateInput` or `CalendarEvent`. Is this a solution or am I missing something here 🤔 ?

**Comment by rofreg** [comment]
I think that mostly works! As you note, the biggest issue is that because the factory doesn't return an actual `CalendarEvent` object, you can't easily reference the created records by their unique ID (which can be nice if you want your factory to generate randomized values for all the other model attributes). That said, using other unique attributes seems like a solid workaround 👍

And yeah, in my experience it's good practice not to tie a test to a specific row ID, unless that specific row was created by the test itself. Otherwise your tests can end up depending on your seeds in a very brittle way, where you make a tiny change to your seed file and suddenly half of your tests fail 😞
