### ISSUE TITLE
Unexpected error when saving empty event

### ISSUE THREAD

**Issue by DoubleCookies** [Sendouc/sendou.ink#415]
![image](https://user-images.githubusercontent.com/12849336/114915213-f704c780-9e2b-11eb-8ac9-5399062243c2.png)
I skip every field and just press "Save".. and get this message. Probably good place for image? (#329)

**Comment by Sendouc** [comment]
Nice find. Yeah the crash image would be nicer. Btw checking the error it comes from React Hook Form error message being an object when I'm treating it as string in code (trying to render an object in React crashes). If you want to you can take a look and submit or fix or I can also do it sometime 👍
