### ISSUE TITLE
Build analyzer: overflows on mobile

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#434]
Seems to overflow when ink res and bomb def are selected in a build:

![image](https://user-images.githubusercontent.com/38327916/115737691-07b9be00-a395-11eb-90e5-3b54af0c6d90.png)

**Comment by DoubleCookies** [comment]
Probably it is OK now. I saw it before and it was connected with tooltips for specific abilities. Tried to fix it earlier but without success.
![image](https://user-images.githubusercontent.com/12849336/124780228-1c94ff00-df4b-11eb-9633-6f16c7def8ba.png)

**Comment by Sendouc** [comment]
Ok cool. We can always reopen if it reappears.
