### ISSUE TITLE
Weapon selector allow searching by sub or special weapon

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#488]
![image](https://user-images.githubusercontent.com/38327916/117580247-cb5dc000-b0ff-11eb-9903-06dcab42b44d.png)

If exact match for example for "Inkjet" (case insensitive) show all weapons with it. Maybe for English initially then later for all languages supported?

**Comment by Red-CS** [comment]
Has anybody started this? And where would this feature be implemented? Along the sidebar with Browser, Tier list, etc., or built into something else?

**Comment by Sendouc** [comment]
If it's not assigned to anyone and nobody commented anything you can think it's up for grabs. The change needs to be made to the `WeaponSelector` component.

**Comment by DoubleCookies** [comment]
I can try to implement this if you wouldn't mind.

**Comment by Sendouc** [comment]
I'd say go unless @Red-CS started already

**Comment by Red-CS** [comment]
> I can try to implement this if you wouldn't mind.

I haven't started, so go ahead, all yours!

**Comment by Sendouc** [comment]
https://github.com/Sendouc/sendou.ink/pull/503
