### ISSUE TITLE
(suggestion) Allow users to make builds with missing ability slots

### ISSUE THREAD

**Issue by jaherron** [Sendouc/sendou.ink#574]
I have some gear that I want to make builds for but they don't have all of their ability slots.
Here's a [screenshot](https://drive.google.com/file/d/1wpD4P3sJXWqYpUMPly5yb3nAyMpOKxIJ/view?usp=drivesdk) (goes to Google Drive) of the build I was trying to make.
There needs to be a way for someone to exclude abilities from builds if their gear doesn't have all of its slots.

**Comment by Sendouc** [comment]
Yeah it probably makes sense to allow that. It has been suggested before as well. Although I'd probably make it so that those builds are hidden on the main /builds page still I imagine mostly people are looking for full builds. Still shown on your own page though.
