### ISSUE TITLE
Calendar: on wide resolution content overflows the screen

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#590]
![image](https://user-images.githubusercontent.com/38327916/126082289-efe221ac-5f97-4ba6-a6c7-c6c0302a2b55.png)

Problematic line is https://github.com/Sendouc/sendou.ink/blob/main/components/common/Calendar.tsx#L67 I think

**Comment by kjhf** [comment]
is this the columns going off screen or the event name being cut?

on the <main> tag there is a max-width set to 64rem. Think this should be fit-content or max-content.
