### ISSUE TITLE
Global CSS cannot be imported from files other than your Custom <App>. Failed to build.

### ISSUE THREAD

**Issue by kjhf** [Sendouc/sendou.ink#666]
./pages/styles.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\_app.tsx

This error occurred during the build process and can only be dismissed by fixing the error.

-----
Full printout from the terminal:
PS D:\User\Projects\sendou.ink> npm run dev

> sendou.ink@1.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\User\Projects\sendou.ink\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

(node:9380) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
error - ./pages/styles.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\_app.tsx

-----

Node version:
node -v
v16.9.1

NPM version:
npm -v
7.24

Running on Windows 10 64-bit

Followed README instructions:
1. Clone the project (running from main)
2. Run npm i to install dependencies
3. Run npm run compile to compile translation files.
4. Run npm run dev to start the development server at http://localhost:3000/. (To stop the server at any time, type Ctrl+C.)

The server spins up however only displays the error message above.

**Comment by Sendouc** [comment]
Hmm yeah like we talked on Discord this is kind of puzzling me. I could try my Windows machine to see if that has any impact. It still looks like to me that somehow TypeScript doesn't "initialise" or something?

**Comment by rkyerevan** [comment]
I have the same problem

**Comment by kjhf** [comment]
Seems to be a breakage with NextJS
use `npm i next@10.2.0`
to revert the Next version and the problem goes away. At time of writing, the current Next version is `11.1.2`.
