### ISSUE TITLE
Builds: wrong order

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#673]
![image](https://user-images.githubusercontent.com/38327916/135140377-b30df567-5f72-47f2-8d34-3b31c12b84a4.png)

Why is the older top 500 build first here? Expected is that Top 500 builds are listed so that newest is shown first.

**Comment by kjhf** [comment]
Couple of thoughts without looking into the code - 
Looking at the other results, it's not like DUDE's entry is an anomaly, as Glacey's entry is not where it should be. So, 
- Check if the ordering is actually happening
- Check if the ordering is by updated date, but data shown is the created date
- Check if there are other ordering flags set, e.g. is DUDE's account a JP account for some reason?

**Comment by Sendouc** [comment]
Good points! I think currently this ticket is how should this work. So planning work for future. As I don't think I'll end up touching this implementation of the feature. For Splat 3 I think we'll group builds of same weapon by same user together. Not quite sure how this UI will look though.
