### ISSUE TITLE
Generate cool build/fa pics

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#73]
https://carbon.now.sh/ something like this for builds/fa's/more?

**Comment by Puffycheeses** [comment]
If we were to tackle this task would we prefer dynamic image generation such as provided by [node-canvas](https://github.com/Automattic/node-canvas) or would we just allow export of profiles & builds as images with [dom-to-image](https://github.com/tsayen/dom-to-image)?

No matter the implementation There'd either be some vector work (node-canvas) or CSS work (dom-to-image) to make some nice exportable images. I've always wanted to learn about image generation so I might give it a go this weekend if I have time but I wanted to get your input on what sort of libraries you'd like you use & what sort of output you'd expect?

**Comment by Sendouc** [comment]
Couple things to note:

a) Free Agents page still needs to be imported to the rewrite (main) branch.
b) Getting the project running locally is not documented at the moment. This is something I need to do.

I can make another post here once I have tackled those.

About the requirements:

1) You should be able to generate some sort of nice looking image that can then be [shared](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) (mobile) or downloaded (PC) using a button on the build / FA card.
2) Hopefully some work can be shared between build and FA card export.

I don't think the actual library/technique used matters much if it just can do 1). Probably doing it on frontend side of things should be sufficient. Alternatively a specialized serverless function can be created.

**Comment by Sendouc** [comment]
I made instructions on how to get the project running locally: https://github.com/Sendouc/sendou.ink#setting-up-the-project-locally

**Comment by Puffycheeses** [comment]
Awesome thanks for the help, I’ll let you know if I run into any issues setting up a local instance.
