### ISSUE TITLE
Description can’t be fully read

### ISSUE THREAD

**Issue by Demotone** [Sendouc/sendou.ink#769]
[Build](https://sendou.ink/u/244811642775273482) 
![0F895EF0-46B6-4D73-ADA6-488BF06CB337](https://user-images.githubusercontent.com/16109139/156151119-7667352d-b002-4456-9bda-76a867a73bfb.jpeg) Difficult to have it appear as well after pressing the description

**Comment by Sendouc** [comment]
Thanks for the report! I'm not developing the old site anymore so I won't fix this. But this is still a good point to keep in mind once I design how builds for the new site should look.
