### ISSUE TITLE
Auth when clicking cancel it leads to an error page

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#824]
Currently when you click "Log in" but on discord.com click "Cancel" it leads you to this kind of page:

![image](https://user-images.githubusercontent.com/38327916/177030620-c2b388f2-a217-41ce-b1db-d1912053c2c6.png)

Instead it should leads us back to sendou.ink UI with some helpful message that says you should approve the log in on Discord.

**Comment by remmycat** [comment]
I added a dialog for this case and other authentication errors in #1022
