### ISSUE TITLE
.avif badge fails to display on Firefox

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#825]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/38327916/177768631-8ab3c325-3fe2-43d8-9ddf-8a164d238a8b.png">

- everything works on Chrome
- everything but this works on Firefox

Why? Fix after figuring out why this one is different. All were created with https://squoosh.app/

**Comment by remmycat** [comment]
Seems to have been an encoding issue with that version of squoosh somehow producing an image firefox wasn't able to decode.

When running the squoosh script mentioned in the Readme again for the badges and clearing my cache, Firefox can render the Squid Junction avif fine again.
I created a PR for re-encoding all avif files: #1018
