### ISSUE TITLE
Allow user to select favorite badge

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#839]
![image](https://user-images.githubusercontent.com/38327916/181524014-bac7fd0e-f03c-424c-bb50-f963e837aa2f.png)

Allow selecting which badge is big on initial user page load.

I expect this task to go something like this:

- Sort badges on user page by badge id on default.
- Create migration to add "favoriteBadgeId" or something to user table. (FK user id, badge id -> BadgeOwner table)
- Favorite badge can be set / removed from /edit user page.
- If favoriteBadgeId exists show badge with that ID first (preferably done in SQL not TypeScript)
- Good to have: E2E test that tests that favorite badge can be set, has expected result, can be removed and the removal also shows.

## User request

![image](https://user-images.githubusercontent.com/38327916/181523916-75af68aa-ccd2-4a6f-a046-04db6d85c5d1.png)

**Comment by zenpk** [comment]
I'm working on this.
