### ISSUE TITLE
Some badge displayNames messed up

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#841]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/38327916/181904458-117786a2-7730-42a9-ae31-a753b3f26145.png">

**Comment by DoubleCookies** [comment]
![image](https://user-images.githubusercontent.com/12849336/198229843-b11e4c67-8c64-4a3b-9358-2de110a41081.png)
Smth wrong with names in db. I can update them if I know correct names.

**Comment by Sendouc** [comment]
Yeah 🤔 It's probably most convenient I update them though.

**Comment by Sendouc** [comment]
Fixed
