### ISSUE TITLE
Focusing minimal button has no outline

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#857]
![image](https://user-images.githubusercontent.com/38327916/184495213-b4eca0c3-7d92-4632-b1e9-c9dd37ec045e.png)

No indication "Add as text" is being tabbed

**Comment by DoubleCookies** [comment]
_Wrong click_

Should all minimal button be updated like "add as text" button?

**Comment by Sendouc** [comment]
Yeah everything you can click with mouse should also be tabbable with outline. Or well the focus indicator can change depending what looks good in the context.
