### ISSUE TITLE
Better default value for another event date

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#858]
Currently when adding a new date to calendar event on http://localhost:5800/calendar/new it is browser default value:

![Image](https://user-images.githubusercontent.com/38327916/193896337-f1921404-6ae6-4cd3-a4de-e825ca5b1d2e.png)

It could be a nicer default if it instead used + 24 hours of old value. I saw some events with messed up day 2 clock since they forgot to update this time. Could either introduce state here or read the value of the previous input via ref.

Also, even the first date should probably default to :00 instead of random minutes

**Comment by ElementUser** [comment]
I can help look into this one & most likely fix it, but it looks like I would need to be "logged in" on the localhost website.

If someone can help me with the steps required to get to the calendar/new page, that would be great :)

**Comment by Sendouc** [comment]
@ElementUser you can mock the log in!

So if you go to http://localhost:5800/admin and then log in as any user it will do the trick.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/38327916/198510133-4c35c5f8-e69d-47dd-813b-113a0d4ad874.png">

Then after you are faking logging in just go to http://localhost:5800/calendar/new

**Comment by remmycat** [comment]
Mostly implemented via #1070 
I'm gonna have a look at this part while doing #1082 
> Also, even the first date should probably default to :00 instead of random minutes`
