### ISSUE TITLE
UserCombobox show just one result if exact discord id match

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#914]
Currently if you search user via Discord ID it just gives multiple:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/38327916/196030511-c9440e21-03b8-40d1-8dac-c63452a1ba74.png">

**Comment by ElementUser** [comment]
I'm reading some of the Fuse documentation & it seems that we can configure how "fuzzy" the logic is with several options.
- Reference: https://fusejs.io/api/options.html

Right now, I tried adjusting the `threshold` option and lowering it, and it seems to make things better overall. How low you want it to go totally depends on what you would like. I'll make a PR shortly so you can see what I did to make the search better in this specific case
