### ISSUE TITLE
French localization WeekLinks out of space

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#935]
Shorter translation? Adjust CSS?

![Image](https://user-images.githubusercontent.com/38327916/189164561-dc94b3e7-32b3-4b73-a8ed-6aa63f139a83.png)

**Comment by DoubleCookies** [comment]
Btw not same, but a bit annoying word break in ru locale
![image](https://user-images.githubusercontent.com/12849336/196382455-21394efc-2a6f-4bf3-bcda-e59d6e61e9dc.png)

**Comment by ElementUser** [comment]
Adjusted CSS to resolve this issue as well in this PR: https://github.com/Sendouc/sendou.ink/pull/1119

**Comment by ElementUser** [comment]
@DoubleCookies I can't read Russian, but I believe my changes in PR !1119 also addresses the edge case for RU strings:

![image](https://user-images.githubusercontent.com/15804376/201445990-7fc2337f-8702-4960-b027-f900b932776d.png)

I will include this image in my PR as well.
