### ISSUE TITLE
[Splatoon 3 Build Analyzer] Changing your build scrolls you all the way back to the top

### ISSUE THREAD

**Issue by nightpool** [Sendouc/sendou.ink#952]
This makes it hard to compare values in-between builds by adding / removing items. 

Steps to reproduce:

1. Navigate to the beta analyzer
2. Open some of the panels and scroll down
3. Change the build
4. See that the entire page jumps and you're scrolled back up to the top, making it hard to compare values side by side.

Thanks again for making this tool!

**Comment by Sendouc** [comment]
Yup I agree it's annoying. I think best way to fix it will be some of the new API's of React Router 6.4.0 like https://reactrouter.com/en/6.4.0/components/scroll-restoration#getkey

So I think we need to wait a bit before fixing it (Remix didn't get React Router 6.4. yet)
