### ISSUE TITLE
Dragging abilities for mobile

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#984]
See discussion in https://github.com/Sendouc/sendou.ink/pull/979

Currently works nicely for desktop but this feature could be really nice if it worked for touch interfaces (mobile phones/tablets) as well.

**Comment by remmycat** [comment]
Seems to be already working fine for me on iOS/Safari 16.0

https://user-images.githubusercontent.com/3317423/195696161-b4e5dd8b-24ab-46b5-b3ea-d424187f814c.MOV

I have to press an icon for a bit until I can move it. If I press to long before moving an ability, it will show a big preview of the image, but I can then still drag it somewhere by moving my finger (this happened at the beginning of the video)

This seems consistent with the iOS system wide drag and drop functionality. If the image preview can be prevented somehow that would make things even easier to use.

**Comment by Sendouc** [comment]
Okay cool to know! Thanks for sharing. Still doesn't seem to work on my phone (Android / Chrome) so I wonder if something is needed specifically for Chrome mobile 🤔 . 

> If the image preview on a long press can be prevented somehow that would make things even easier to use. Maybe pointer-events: none on the img tag or something?

This is a cool point and for sure would be nice to disable that if we can figure out how.
