### ISSUE TITLE
StatCard titles not aligned

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#987]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/38327916/193477373-7185663b-3d75-407b-bd4f-86ae33025668.png">

Without ability StatCard visuals bugged. Base / Build titles should be on same line for every card ability or no (empty space at the bottom if no ability for that StatCard).

**Comment by curtgrimes** [comment]
Just to verify, it should look like this, correct?

<img width="552" alt="CleanShot 2022-10-03 at 22 58 51@2x" src="https://user-images.githubusercontent.com/3038600/193745429-a4fdbe79-fdde-47ef-98c2-5256e5acd23c.png">
