### ISSUE TITLE
Unnecessary scrollbar on homepage cards (Chrome 106.0.5249.103) (125% zoom)

### ISSUE THREAD

**Issue by justintricate** [Sendouc/sendou.ink#999]
The topmost cards are giving an unnecessary scrollbar, with no ability to scroll:

![image](https://user-images.githubusercontent.com/47122570/194537961-8986761f-6f81-445e-aa77-9f8f87f1bd52.png)

**Comment by justintricate** [comment]
For .front_builds-wrapper, overflow-x being set to 'hidden' will fix this:

![image](https://user-images.githubusercontent.com/47122570/194538611-072c0366-8f19-47f7-8219-e5162c2611e7.png)

**Comment by Sendouc** [comment]
Good point 👍
